### ISSUE TITLE
How to use run_continuiously?

### ISSUE THREAD

**Issue by Messi10AP** [dbader/schedule#70] opened 2015-11-08 15:15 UTC
What is the syntax to use the run_continuously function? I tried run_continuously(name) and run_continuously(schedule.every().day.at("00:30").do(name)) but both didnt work. Also, where do i put the function?

**Comment by dbader** [comment] 2015-11-09 01:55
Looks like this is a dupe of #69. Let's continue the discussion over there.

**Closed by dbader** 2015-11-09 01:55 UTC
