### ISSUE TITLE
Add api to start scheduler in a separate Thread 

### ISSUE THREAD

**Issue by msoedov** [dbader/schedule#100] opened 2016-10-14 20:25 UTC
I've noticed common pattern across my services with `schedule` where I use the following block

``` python
while True:
    schedule.run_pending()
    time.sleep(1)
```

as

``` python

....
def spawn():
    while True:
        schedule.run_pending()
        time.sleep(1)

if __name__ == '__main__':
   Thread(target=spawn).start()
   ....
```

to schedule some tasks but continue running code in the main thread. I think will be really useful to  have `spawn` method in the library

**Comment by dbader** [comment] 2016-11-09 13:58
Linking this to #94 

Also posting this FAQ item for reference: https://github.com/dbader/schedule/blob/master/FAQ.rst#how-to-continuously-run-the-scheduler-without-blocking-the-main-thread

**Comment by dbader** [comment] 2016-11-09 14:01
Never mind, let's close this in favor of #69 because it's practically a duplicate of this issue and has a longer discussion thread already.

Thank you @msoedov

**Closed by dbader** 2016-11-09 14:01 UTC
Labels: enhancement
