### ISSUE TITLE
Scheduled tasks are not called anymore

### ISSUE THREAD

**Issue by madfatcat** [dbader/schedule#172] opened 2017-10-26 07:39 UTC
Everything was fine, but on the last week scheduling stopped working. I made some testing:
I have a script which defines few scheduled tasks. When running from command string this way: `python myscript.py` schedule work just fine. But when I run this script from another script: 
`newprocess="nohup python myscript.py"
os.system(newprocess)`
the scheduled tasks are not called there.
in myscript.py, schedule is performed in a separate thread:
`def scheduler_function():
    while 1:
        schedule.run_pending()
        time.sleep(1)

thread = Thread(target = scheduler_function, args = ())
thread.start()`

Can you please help me with this?

**Comment by candyfaz** [comment] 2017-10-26 07:58
This might sound really stupid. But can you change this as: 
`nohup python myscript.py &> /dev/null &`
Instead of what you are doing above. 

My guess is you are terminating the process. Run it as a background process.

**Comment by madfatcat** [comment] 2017-10-26 08:03
Thanks for your suggestion, but there are a lot of another logic in myscript.py and it's functioning correctly, so the process is definitely performing.

**Comment by candyfaz** [comment] 2017-10-26 08:10
I don't wish to assume, but looks to me that it is some thread issue -
1. More like adding thread.join(). 
2. And the way you are initialising schedule within the thread. 
>  if you could point me to your github repo. I might be able to help you.

**Comment by madfatcat** [comment] 2017-10-26 08:13
Thanks again man, I'll check once again.

**Comment by madfatcat** [comment] 2017-10-26 19:42
candyfaz, I'm actually running myscript.py in background, just forgot to add & in my message. However, I don't know why, but adding `&> /dev/null` fixed the problem.

**Comment by candyfaz** [comment] 2017-10-27 02:39
I won't be able to answer that question, unless I look at your code. However, if the package is running as intended kindly close the issue. Happy to help !!

**Comment by madfatcat** [comment] 2017-10-27 07:00
Oops, it stopped working again. After restarting the script everything works fine, but after definite time the scheduled tasks stop calling. It's a simple script on Raspberry Pi which controls lights, alarm etc. I should mention that the script was working fine for months and then scheduled tasks stopped performing without any changes in script. I'll appreciate if  you take a look at my script, how can I share it? There's no repo.

**Comment by lutzhorn** [comment] 2017-10-27 07:05
On Fri, Oct 27, 2017 at 07:00:12AM +0000, madfatcat wrote:
> I'll appreciate if  you take a look at my script, how can I share it?
> There's no repo.

You can create a Gist at https://gist.github.com/

**Comment by madfatcat** [comment] 2017-10-27 07:22
Here's my script as is: https://gist.github.com/madfatcat/da45de83eb608a56797397993c21d501
Please note it's very lame cause this is my first python experience and created in haste. )

**Comment by lutzhorn** [comment] 2017-10-27 07:30
From just reading your code it is hard to tell what can cause the
problem you observer.

Could you create a minimal running example that also causes the problem
(see http://sscce.org/)? If you are able to reproduce the problem with
less code that is not releated, it would greatly help us helping you.

Also please add more information about the exact versions of Python and
the relevant libraries you use.

**Comment by madfatcat** [comment] 2017-10-28 08:02
Now I write a record to the log every minute in a thread where `schedule.run_pending()` is called. According to the logs, after several hours of execution of my script the thread with `schedule.run_pending()` stopped writing log records. It seems that the thread simply stopped executing for some reason. 
`def scheduler_function():
    while 1:
        schedule.run_pending()
        time.sleep(1)`

`if __name__ == "__main__":
		thread = Thread(target = scheduler_function, args = ())
		thread.start()`

**Comment by candyfaz** [comment] 2017-10-28 11:04
@madfatcat - Then the most simple explanation for this is that **something** (an exception etc) is terminating the **main thread** of your program causing the other threads to abruptly exit as well. 

Hopefully you figure out the issue, as your sample code is too huge to go through entirely. Kindly close the issue as it seems unrelated to the library package. 

> I'm using the schedule package on a production environment for the past month and it hasn't caused such issues that you've mentioned. 

> If you could simplify your code. I will happily look into it

**Closed** 2017-10-29 05:14 UTC
